name: "Code Quality: Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Run `terraform fmt`
        run: terraform fmt -diff -check -no-color -recursive

      - name: Run `terraform init`
        run: terraform init -backend=false -get=true

      - name: Run `terraform validate`
        run: terraform validate -no-color

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.0.2
        with:
          tfsec_args: --soft-fail
          github_token: ${{ secrets.GITHUB_TOKEN }}
